gestion_git/urls.py
from django.contrib import admin
from django.urls import path, re_path
from gestion_git import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from gestion_git.views import MainView
from django.conf.urls.static import static 


urlpatterns = [
    # BASE
    path('base', views.base, name='base'),

    # Registro y Login/out
    path('register', views.pagina_de_registro, name='register'),
    path('login/',views.pagina_de_login, name= 'login'),
    path('logout/',views.pagina_de_logout, name= 'logout'),

    # Usuarios
    path('users/', views.pagina_usuario, name='users'),
    
    # Mandatarios
    path('crear_seccion/',views.crear_seccion, name="crear_seccion"),
    path('secciones/', views.secciones_git, name='secciones'),
    path('seccion/<str:pk_seccion>', views.seccion_manda, name='seccion'),
   

    # Expedientes
    path('crear_expediente_seccion/<str:pk>/',views.crear_expediente_git_seccion, name='crear_expediente_seccion'),
    path('expediente_git/<str:pk>/', views.ver_expediente_git, name="expediente_git"),
    path('editar_expediente_git/<str:pk>/', views.editar_expediente_git, name='editar_expediente_git'),
    path('expediente_git_global',views.expedientes_git, name="expediente_git_global"),
    path('exportar_adjudicaciones/',views.exportar_embargos, name="exportar_adjudicaciones"),
    path('importar_expe_git/',views.importar_expediente_git, name="importar_expe_git"),

    # Planes de Pago
    path('planes', views.planes_de_pago, name="planes"),
    path('nuevo_plan_adj/<str:pk>/',views.plan_adjudicacion, name="nuevo_plan_adj"),
    path('actualizar_plan/<str:pk>/',views.actualizar_plan, name='actualizar_plan'),
    path('eliminar_plan/<str:pk>/',views.eliminar_plan, name='eliminar_plan'),
    path('planes/<str:pk>/',views.ver_planes,name='planes_sec'),
    path('nuevo_plan_seccion/<str:pk>/',views.nuevo_plan, name="nuevo_plan_seccion"),
    re_path(r'^exportar_planes/',views.exportar_planes, name="exportar_planes"),
    path('importar_planes/',views.importar_planes, name="importar_planes"),
    path('',views.MainView.as_view(), name='main-view'),
    path('subir_comprobantes/',views.subir_comprobantes, name='subir_comprobantes'),
    path('get_comprobantes/<str:pk>/',views.get_comprobantes, name='get_comprobantes'),
    path('cambiar_estado_plan/', views.cambiar_estado_plan, name="cambiar_estado_plan"),
    path('cambiar_fact_plan/', views.cambiar_fact_plan, name="cambiar_fact_plan"),
     

    # Embargos
    path('embargos/',views.embargos,name="embargos"),
    path('embargos/<str:pk>/',views.ver_embargo,name='embargos_sec'),
    #path('nuevo_embargo/<str:pk>/',views.nuevo_embargo, name="nuevo_embargo"),
    path('nuevo_embargo_adj/<str:pk>/',views.embargo_adjudicacion, name="nuevo_embargo_adj"),
    path('actualizar_embargo/<str:pk>/',views.actualizar_embargo, name='actualizar_embargo'),
    path('eliminar_embargo/<str:pk>/',views.eliminar_embargo, name='eliminar_embargo'),
    re_path(r'^exportar_embargos/',views.exportar_embargos, name="exportar_embargos"),
    path('cambiar_estado_embargo/', views.cambiar_estado_embargo, name="cambiar_estado_embargo"),
     

    # CBU Contribuyentes
    path('cbu_contribuyentes/',views.cbu_contribuyente, name="cbu_contribuyentes"),
    
    # Recuperar Usuario y Password
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='gestion_git/accounts/password_reset.html'), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='gestion_git/accounts/accountspassword_reset/done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='gestion_git/accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done',auth_views.PasswordResetCompleteView.as_view(template_name='gestion_git/accounts/password_reset_done.html'), name='password_reset_complete'),

    # Para contribuyentes
    path('comprobantes/', views.subir_comprobantes_view, name="subir_comprobantes_view"),
    path('seg-embargo/<str:pk>', views.seg_embargo, name="seg_embargo"),

    # Patentes
    path('subir-patentes/', views.subir_patentes, name="subir_patentes"),
    path('patente/<str:dominio>/', views.ver_patente, name="ver_patente"),
]

urlpatterns += static(settings.MEDIA_URL,  
                          document_root=settings.MEDIA_ROOT)

gima/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import include, path, re_path
from gestion_git.views import pagina_de_login
from gestion_git.views import MainView, subir_comprobantes
from gestion_git import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion_git/', include(('gestion_git.urls','git'))),
    path('', pagina_de_login, name='login'),
    path('gestion_git/accounts', include('django.contrib.auth.urls')),    
    path('__debug__/', include('debug_toolbar.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gestion_git/models.py
from django.db import models
from tokenize import blank_re
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT, RESTRICT, SET_NULL
from django.forms import EmailField
from django.db.models.fields.related import ForeignKey
from django.db.models.fields.files import FileField
from .choices import *
from django.contrib.auth.models import User

# Create your models here.
class Seccion(models.Model):
    #user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    cuit = models.CharField(max_length= 12,null= True, blank=True)
    seccion = models.CharField(null= False, blank=False, max_length=3,primary_key=True)
    e_mail = models.EmailField(blank=True, null= True)
    e_mail_agip = models.EmailField(blank=False)
    foto_user = models.ImageField(null=True, blank=True)
    direccion = models.CharField(max_length=150)
    telefono = models.CharField(max_length=150)

    def __str__(self):
        return str(self.seccion)
    class Meta:
        ordering= ('seccion',)

class UserSeccion(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    seccion = models.ForeignKey(Seccion, null=True, on_delete=models.SET_NULL)

class Adjudicacion(models.Model):
    cuit = models.CharField(max_length=13, null= False, blank=False)
    apellido_nombre	= models.CharField (max_length=200, null=True, blank=True)
    adjudicacion = models.CharField (null= False, blank=False, max_length=30, primary_key=True)
    solicitud =	models.CharField (max_length=45, null= True, blank=True)
    nro_inscripto =	models.CharField (max_length=45, null= True, blank=True)
    dominio = models.CharField (max_length=20, null= True, blank=True)
    desc_adj = models.CharField (max_length=45, null= True, blank=True)
    cod_imp =  models.CharField (choices= impuestos ,max_length=15, null= True, blank=True)
    seccion = models.ForeignKey(Seccion, null=True, on_delete=models.SET_NULL)
    mandatario = models.CharField(max_length=100, null= True, blank=True)
    juzgado = models.CharField (choices= juzgados, null= True, blank=True, max_length=10)
    oficio = models.CharField (max_length=45, null=True, blank=True)  
    secretaria = models.CharField (choices= secretarias, null= True, blank=True, max_length=2)
    estado_juicio = models.CharField (max_length=45, null= True, blank=True)
    f_inicio_juic =	models.DateField (null= True, blank=True)
    fecha_adj =	models.DateField (null= True, blank=True)
    tipo_adm = models.CharField (max_length=45, null= True, blank=True)
    exp_adm	= models.CharField (max_length=45, null= True, blank=True)
    año_adm	= models.CharField (max_length = 10, null= True, blank=True)
    nro_exp = models.CharField (max_length=45, null= True, blank=True)
    año_exped =	models.CharField (max_length=10, null= True, blank=True)
    imp_nominal	= models.DecimalField(max_digits=20, decimal_places=2,null= True, blank=True)
    calle =	models.CharField (max_length=200, null= True, blank=True)
    puerta = models.CharField (max_length=45, null= True, blank=True)
    piso = models.CharField (max_length=45, null= True, blank=True)
    dpto = models.CharField (max_length=45, null= True, blank=True)
    oficina = models.CharField (max_length=45, null= True, blank=True)
    localidad = models.CharField (max_length=45, null= True, blank=True)
    cod_post = models.CharField (max_length=45, null= True, blank=True)
    const_deuda=models.FileField(upload_to='expedientes_git/constancias/',blank=True, null=True)
    date_created= models.DateTimeField(auto_now_add=True, null=True)
    

    def __str__(self):
        #return (self.apellido_nombre)
        return str(self.adjudicacion)
    class Meta:
        ordering= ['-f_inicio_juic','adjudicacion','-imp_nominal']

class Embargos(models.Model):
    #seccion = models.CharField(Seccion, on_delete=PROTECT)
    adjudicacion = models.ForeignKey(Adjudicacion, max_length=45,on_delete=PROTECT, blank=False, null=False)
    tipo_de_embargo = models.CharField (choices = tipo_de_embargo,default='preventivo', max_length=45, blank=False, null=False)
    clase_embargo = models.CharField (choices= clase_embargo, default="SOJ",max_length=45, null= True, blank=True)
    monto_embargado = models.DecimalField(max_digits=12, decimal_places=2,null= False, blank=False)
    estado = models.CharField (choices = estado_embargo, default="Trabado", max_length=45, null= True, blank=True)
    fecha_pedido_git = models.DateField(verbose_name="Fecha pedido de Embargo",blank=True, null=True)
    fecha_acreditacion= models.DateField(blank=True, null=True)
    fecha_pedido_levantamiento= models.DateField(verbose_name="Fecha pedido de Levantamiento",blank=True, null=True)
    orden_levantamiento = models.CharField (choices= orden_de_levantamiento, default='no',max_length=45, null=True, blank=True)
    fecha_levantamiento_git = models.DateField(blank=True, null=True)
    oficio_embargo= FileField(upload_to='embargos/oficios/',blank=True, null=True)
    oficio_lev_embargo = FileField(upload_to='embargos/ofic_levantamiento',blank=True, null=True)
    dia_ingreso_embargo= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.adjudicacion)

    class Meta:
        ordering = ('-fecha_pedido_git',) 

class Planes_de_pago(models.Model):
    #seccion = models.ForeignKey(Seccion, null=True, on_delete=models.SET_NULL)
    adjudicacion = models.ForeignKey(Adjudicacion, max_length=45,on_delete=PROTECT, blank=False, null=False)
    imp_actualizado = models.DecimalField (max_digits=12,decimal_places=2, null= False, blank=False)
    fecha_de_suscripcion = models.DateField(blank=False, null=False)
    modalidad_de_pago = models.CharField (max_length=45, choices = mod_pago,default='Contado', null=True, blank=True) 
    cantidad_de_cuotas_plan = models.CharField (max_length=2, choices=cuotas, default='1', null=True, blank=True)
    honorarios_mandatario = models.DecimalField (max_digits=10,decimal_places=4, default='22212.81',null= True, blank=True)
    honorarios_procuracion = models.DecimalField (max_digits=10,decimal_places=4, default='7867.58',null= True, blank=True)
    fecha_de_pago_honorarios = models.DateField(blank= True, null= True)
    cuotas_de_honorarios = models.CharField (null= True, blank= True,choices= cuotas_hono, default= '1',max_length=2)
    acredito_comprobante = models.CharField(max_length=2, choices= comprobante, default='no',blank=True, null=True)
    estado_del_plan = models.CharField(max_length = 20, choices= estado_plan, default='Pendiente',blank=True, null=True)
    fecha_de_cancelacion = models.DateField(null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    telefono = models.CharField (max_length= 15,null = True, blank= True)
    celular = models.CharField (max_length= 15,null = True, blank = True)
    archivo_plan= models.FileField(upload_to='planes/planes_de_pago/', blank=True, null=True)
    comprobantes = models.FileField(upload_to='planes/comprobantes/', blank=True, null=True)
    dia_ingreso_plan= models.DateTimeField(auto_now_add=True, null=True, blank=True)
    facturado = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return str(self.adjudicacion)
    
    class Meta:
        ordering = ('-fecha_de_suscripcion',)


class Comprobantes_de_Pago(models.Model):
    adjudicacion = models.ForeignKey(Adjudicacion, null=True, blank=True, on_delete=models.PROTECT)
    comprobantes = models.FileField(upload_to='planes/comprobantes/', blank=True, null=True)
    dia_ingreso_comprobante= models.DateTimeField(auto_now_add=True, null=True, blank=True)


class Cbu_Contribuyente(models.Model):
    seccion = models.CharField(max_length= 3, null= True, blank=True)
    #seccion = models.ForeignKey(Seccion, null=True, on_delete=models.SET_NULL)
    cuit= models.CharField(null= False, blank= False,max_length=15)
    demandado = models.CharField(max_length= 200, null= True, blank=True)
    impuesto = models.CharField(max_length=3, blank= True, null= True)
    adjudicacion= models.ForeignKey(Adjudicacion,on_delete=models.PROTECT, blank=True, null=True)
    #adjudicacion=models.CharField(max_length=20, null=True, blank=True)
    cbu = models.CharField(max_length=30,blank=False, null=False)
    banco = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        #return (self.apellido_nombre)
        return str(self.cuit)
    class Meta:
        ordering= ['banco','cuit','impuesto']

class Patente(models.Model):
    seccion = models.ForeignKey(Seccion, null=True, on_delete=models.SET_NULL)
    dominio = models.CharField(max_length= 10, null= True, blank=True)
    vigente=models.BooleanField()
    titular = models.CharField(max_length=200, blank=False, null=False)
    cuit = models.CharField(max_length=100, blank=False, null=False)
    direccion = models.CharField(max_length=200, blank=False, null=False)
    localidad = models.CharField(max_length=200, blank=False, null=False)
    provincia = models.CharField(max_length=200, blank=False, null=False)
    cpa = models.CharField(max_length= 10, null= True, blank=True)
    marca = models.CharField(max_length= 200, null= True, blank=True)
    modelo = models.CharField(max_length= 200, null= True, blank=True)
    rad= models.CharField(max_length= 100, null= True, blank=True)
    pje_tit=models.FloatField(null= True, blank=True)
    fecha = models.DateField(null=True, blank=True)

templates/gestion_git/crear_expediente.html
{% extends "base.html" %}
{% block title %} GIMA{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

{% load static %}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h2>Cargar Nuevo Expediente GIT para el Mandatario: {{seccion.nombre}} {{seccion.apellido}}</h2>
        </div>
    </div>
</div>
<br/>
{% if submitted %}

<div class="container-sm">
    <div class="card">
        <div class="card-header">
            <h5>La operación se realizó con éxito!</h5>
        </div>
    </div>
</div>

{% else %}
<div class="container-fluid">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class='col-md-12'>
                <div class="form-row">
                    <div class="form-group col-md-1">
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.seccion | as_crispy_field }}
                        {{ crear_expediente_form.juzgado | as_crispy_field }}                    
                        {{ crear_expediente_form.año_adm | as_crispy_field }}
                        {{ crear_expediente_form.cod_post | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.adjudicacion | as_crispy_field }}
                        {{ crear_expediente_form.secretaria | as_crispy_field }}
                        {{ crear_expediente_form.tipo_adm | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.cuit | as_crispy_field }}
                        {{ crear_expediente_form.nro_exp | as_crispy_field }}
                        {{ crear_expediente_form.exp_adm | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2">
                        {{ crear_expediente_form.apellido_nombre | as_crispy_field }}     
                        {{ crear_expediente_form.f_inicio_juic | as_crispy_field }}
                        {{ crear_expediente_form.calle | as_crispy_field }}
                        {{ crear_expediente_form.const_deuda | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.cod_imp | as_crispy_field }}
                        {{ crear_expediente_form.oficio | as_crispy_field }}
                        {{ crear_expediente_form.puerta | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.dominio | as_crispy_field }}
                        {{ crear_expediente_form.solicitud | as_crispy_field }}
                        {{ crear_expediente_form.piso | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.nro_inscripto | as_crispy_field }}
                        {{ crear_expediente_form.fecha_adj | as_crispy_field }}
                        {{ crear_expediente_form.dpto | as_crispy_field }}
                    </div>
                    <div class="form-group col-md-1">
                        {{ crear_expediente_form.imp_nominal | as_crispy_field }}
                        {{ crear_expediente_form.estado_juicio | as_crispy_field }}
                        {{ crear_expediente_form.oficina | as_crispy_field }}
                    </div><div class="form-group col-md-1">
                        {{ crear_expediente_form.desc_adj | as_crispy_field }}
                        {{ crear_expediente_form.año_exped | as_crispy_field }}
                        {{ crear_expediente_form.localidad | as_crispy_field }}
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-right">
                        <input type = "submit" value= "Cargar" class = "btn btn-secondary">
                    </div>
                </div>
            </div>        
        </div>    
    </form> 
</div>
{%endif%}

{% endblock %} 

templates/gestion_git/crear_seccion.html
{% extends "base.html" %}
{% block title %} GIMA{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

{% load static %}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h2>Cargar Nueva Sección</h2>
        </div>
    </div>
</div>
<br/>

{% if submitted %}

<div class="container-sm">
    <div class="card">
        <div class="card-header">
            <h5>La operación se realizó con éxito!</h5>
        </div>
    </div>
</div>

{% else %}

<div class="container-fluid">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            
            <div class='col-md-8'>
                <div class="form-row"> 
                    {{crear_seccion_form|crispy}}
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-right">
                    <input type = "submit" value= "Cargar" class = "btn btn-secondary">
                </div>
            </div>
        </div>
    </form>          
</div>
{%endif%}
    

{% endblock %} 

templates/gestion_git/detalle_patente.html
{% extends "base.html" %}
{% block title %} GIMA {% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="card-header">
        <h4 class="card-title">Dominio: {{dominio}} - Seccion: {{seccion}}</h4> 
      </div>
</div>

<div class="container">
    {%for patente in patentes%}
    <div class="card mt-3">
        <div class="card-header">
        <h4 class="card-title">Titular: {{patente.titular}} - CUIT: {{patente.cuit}}</h4> 
        </div>
        <div class="card-body">    
            <div class="row">
                <div class="col-sm">
                    <p class="text-md-left"><strong> Dirección:</strong> {{patente.direccion}}</p>
                    <p class="text-md-left"><strong> Localidad: </strong>{{patente.localidad}}</p>
                </div>
                <div class="col-sm">
                    <p class="text-md-left"><strong> Provincia:</strong> {{patente.provincia}}</p>
                    <p class="text-md-left"><strong> Código Postal:</strong> {{patente.cpa}}</p>
                </div>
                <div class="col-sm">
                    <p class="text-md-left"><strong> Marca:</strong> {{patente.marca}}</p>
                    <p class="text-md-left"><strong> Modelo:</strong> {{patente.modelo}}</p>
                </div>
            </div>    
            <div class="row">
                <div class="col-sm">
                    <p class="text-md-left"><strong> R.S. Tit./Rad.:</strong>{{patente.rad}}</p> 
                    <p class="text-md-left"><strong> Estado:</strong> {% if patente.vigente %} Vigente {% else %} No vigente {% endif %}</p> 
                    
                </div>
                <div class="col-sm">
                    <p class="text-md-left"><strong> Pje. Tit.:</strong> {{patente.pje_tit}}%</p>
                    
                </div>
                <div class="col-sm">
                    <p class="text-md-left"><strong> Fecha:</strong> {{patente.fecha}}</p>
                </div>
                
            </div>
            <br>
            <div class="row">
                <div class="col-sm">
                    <p class="text-md-left"><a class="btn btn-outline-success" href="">Editar</a></button></p>
                    <p class="text-md-left"><a class="btn btn-outline-danger" href="">Eliminar</a></button></p>
                </div>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}
</div>


{% endblock %} 

templates/gestion_git/eliminar_embargo.html
{% extends "base.html" %}
{% block title %} GIMA{% endblock %}
{% block content %}
{% load static%}
{% load crispy_forms_tags%}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3>Eliminar Embargo</h3>
        </div>
<br>
    <p>¿Estas seguro que deseas eliminar el embargo trabado en el expediente <strong>"{{embargos}}"</strong>?</p>

    <div class="container-sm">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-6">
                <form action= "{% url 'git:eliminar_embargo' embargos.id %}" method="POST">
                    {% csrf_token %}
                    <a href="{% url 'git:embargos' %}">Cancelar</a>
                    
                    <input type="submit" name="Confirmar">
                </form>
            </div>
            <div class="col">
            </div>
        </div>
    </div>      



{% endblock %} 

templates/gestion_git/eliminar_plan.html
{% extends "base.html" %}
{% block title %} GIMA{% endblock %}
{% block content %}
{% load static%}
{% load crispy_forms_tags%}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3>Eliminar Plan</h3>
        </div>
<br>
    <p>¿Estas seguro que deseas eliminar el plan suscripto"{{planes}}"?</p>

    <div class="container-sm">
        <div class="row">
            <div class="col">
            </div>
            <div class="col-6">
                <form action= "{% url 'git:eliminar_plan' planes.id %}" method="POST">
                    {% csrf_token %}
                    <a href="{%  url 'git:planes' %}">Cancelar</a>
                        <input type="submit" name="Confirmar">
                </form>
            </div>
            <div class = "col">
            </div>
        </div>
    </div>

{% endblock %} 

templates/gestion_git/nuevo_plan.html
{% extends "base.html" %}
{% block title %} GIMA{% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3>Cargar Nuevo Plan</h3>
        </div>
    </div>
</div>        
<br/>
{% if submitted %}
<div class="container-sm">
    <div class="card">
        <div class="card-header">
            <h5>La operación se realizó con éxito!</h5>
        </div>
    </div>
</div>        
        {% else %}
        <div class="container-fluid row">
            <div class="col-md-8">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class='col-md-12'>
                            <div class="form-row">
                                <div class="form-group col-md-1">
                                </div>
                                <div class="form-group col-md-2">
                                    <div id="div_id_seccion" class="form-group">
                                        <label for="id_seccion" class=" requiredField">
                                            Seccion<span class="asteriskField">*</span>
                                        </label>
                                        <input name="seccion" class="form-control" id="id_seccion" required 
                                            readonly value="{{adjudicacion.seccion_id}}"
                                        />
                                    </div>
                                    {{ form_plan.modalidad_de_pago | as_crispy_field }}
                                    {{ form_plan.cuotas_de_honorarios | as_crispy_field }}
                                </div>
                                <div class="form-group col-md-2">
                                    <div id="div_id_adjudicacion" class="form-group">
                                        <label for="id_adjudicacion" class=" requiredField">
                                            Adjudicación<span class="asteriskField">*</span>
                                        </label>
                                        <input name="adjudicacion" class="form-control" id="id_adjudicacion" required 
                                            readonly value="{{adjudicacion}}"
                                        />
                                    </div>
                                    {{ form_plan.cantidad_de_cuotas_plan | as_crispy_field }}
                                    {{ form_plan.honorarios_mandatario | as_crispy_field }}
                                </div>
                                <div class="form-group col-md-2">
                                    {{ form_plan.fecha_de_suscripcion | as_crispy_field }}
                                    {{ form_plan.email | as_crispy_field }}
                                    {{ form_plan.honorarios_procuracion | as_crispy_field }}                              
                                </div>
                                <div class="form-group col-md-2">
                                    {{ form_plan.imp_actualizado | as_crispy_field }}
                                    {{ form_plan.celular | as_crispy_field }}
                                    {{form_plan.fecha_de_pago_honorarios | as_crispy_field }}  
                                </div>
                                <div class="form-group col-md-2">
                                    {{ form_plan.estado_del_plan | as_crispy_field }}                               
                                    {{ form_plan.archivo_plan | as_crispy_field }}
                                </div>
                            </div>
                            <!--<div class="form-row">
                                <div class="form-group col-md-2">
                                    <div id="div_id_comprobantes" class="form-group">
                                        <label for="id_comprobantes" class="">
                                            Subir Comprobantes de Pago
                                        </label>
                                        <div class="dropzone" id="MyDrpzone">
                                            <div class="fallback">
                                                <input name="comprobantes" type="file" multiple />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>-->
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <input type = "submit" value="Cargar" class = "btn btn-secondary" id="submit-btn">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                
                </form>
            </div>
            <div class="col-md-4">

                <div class="card-header bg-secondary text-center text-white ">
                    <h4>Subir Comprobantes de Pago</h4>
                </div> 
                <div class="card bg-light border border-dark">
                <br>
                <form action="{% url 'git:subir_comprobantes' %}" method= "POST" class="dropzone" id="MyDrpzone">
                    {% csrf_token %}
                    <input type="hidden" name="adjudicacion" value="{{adjudicacion}}" />
                    <div class="fallback">
                    <input name="file" type="file" multiple />
                    </div>
                </form>
            </div>
        </div>
        </div>

{% endif %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-left">
                <a href="{% url 'git:planes' %}"><strong> Volver </strong></a>
            </div>
        </div>
    </div>        

<script type="text/javascript">
    $(document).ready(()=>{
        $('#submit-btn').on('click',()=>{
            $('#MyDrpzone').submit()
        })
    })
</script>
{% endblock %} 